--01. DDL
CREATE TABLE Clients(
ClientId INT PRIMARY KEY IDENTITY,
FirstName VARCHAR(50) NOT NULL,
LastName VARCHAR(50) NOT NULL,
Phone  VARCHAR(12) NOT NULL CHECK(LEN(Phone) = 12)
)
CREATE TABLE Mechanics(
MechanicId  INT PRIMARY KEY IDENTITY,
FirstName VARCHAR(50) NOT NULL,
LastName VARCHAR(50) NOT NULL,
[Address]  VARCHAR(255) NOT NULL
)
CREATE TABLE Models(
ModelId INT PRIMARY KEY IDENTITY,
[Name] VARCHAR(50) UNIQUE NOT NULL
)
CREATE TABLE Jobs(
JobId INT PRIMARY KEY IDENTITY,
ModelId INT FOREIGN KEY REFERENCES Models(ModelId) NOT NULL,
[Status] VARCHAR(11) CHECK([Status] IN ('Pending', 'In Progress', 'Finished')) NOT NULL DEFAULT 'Pending',
ClientId INT FOREIGN KEY REFERENCES Clients(ClientId) NOT NULL,
MechanicId INT FOREIGN KEY REFERENCES Mechanics(MechanicId),
IssueDate DATE NOT NULL,
FinishDate DATE
)
CREATE TABLE Orders(
OrderId INT PRIMARY KEY IDENTITY,
JobId INT FOREIGN KEY REFERENCES Jobs(JobId) NOT NULL,
IssueDate DATE,
Delivered BIT NOT NULL DEFAULT 0
)
CREATE TABLE Vendors(
VendorId INT PRIMARY KEY IDENTITY,
[Name] VARCHAR(50) NOT NULL UNIQUE
)
CREATE TABLE Parts(
PartId INT PRIMARY KEY IDENTITY,
SerialNumber VARCHAR(50) NOT NULL UNIQUE,
[Description] VARCHAR(255),
Price DECIMAL(6, 2) NOT NULL CHECK(Price > 0),
VendorId INT NOT NULL FOREIGN KEY REFERENCES Vendors(VendorId),
StockQty INT NOT NULL CHECK(StockQty >= 0) DEFAULT 0
)
CREATE TABLE OrderParts(
OrderId INT NOT NULL FOREIGN KEY REFERENCES Orders(OrderId),
PartId INT NOT NULL FOREIGN KEY REFERENCES Parts(PartId),
Quantity INT NOT NULL CHECK(Quantity > 0) DEFAULT 1,
PRIMARY KEY(OrderId, PartId)
)
CREATE TABLE PartsNeeded(
JobId INT NOT NULL FOREIGN KEY REFERENCES Jobs(JobId),
PartId INT NOT NULL FOREIGN KEY REFERENCES Parts(PartId),
Quantity INT NOT NULL CHECK(Quantity > 0) DEFAULT 1,
PRIMARY KEY(JobId, PartId)
)
